services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # enables Docker container widget
      - ./homarr/appdata:/appdata
    ports:
      - '7575:7575'
    environment:
      - TZ=${TZ:-America/New_York}
      - AUTH_SECRET=${AUTH_SECRET}
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}

  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    volumes:
      - ./overseerr/config:/config
    ports:
      - '5055:5055'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - ./radarr/config:/config
      - ./downloads:/downloads
      - ./media/movies:/movies
    ports:
      - '7878:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
